rucpy/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    ##==============APP RUCS================
    url(r'^rucs/', include("rucs.urls", namespace="rucs")),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name="home"),
    url(r'^admin/', include(admin.site.urls)),
]

rucs/urls.py
from django.conf.urls import patterns, url, include
from rucs.views import ruc_detail



urlpatterns = patterns('',
   url(r'^ruc/(?P<ci>\d+)/$', ruc_detail, name='detail'),
) 

rucs/models.py
from django.db import models

# Create your models here.
class Ruc(models.Model):
    ci = models.CharField(max_length=50, db_index=True)
    name = models.CharField(max_length=300)
    dv = models.IntegerField()

rucs/views.py
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from rucs.serializers import RucSerializer
from rest_framework.renderers import JSONRenderer
from rucs.models import Ruc

class JSONResponse(HttpResponse):
    def __init__(self, data, **kwargs):
        content = JSONRenderer().render(data)
        kwargs['content_type'] = 'application/json'
        super(JSONResponse, self).__init__(content, **kwargs)
        
        
@csrf_exempt
def ruc_detail(request, ci):
    
    print ci
    
    ruc_object = Ruc.objects.filter(ci=ci)
    
    if len(ruc_object)>0:
        ruc_object = ruc_object[0]
    else:
        ruc_object = Ruc()
    
    if request.method == 'GET':
        serializer = RucSerializer(ruc_object)
        return JSONResponse(serializer.data)

templates/index.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>RUCpy</title>
	</head>
	
	<body>
		{% load staticfiles %}
		<script src="{% static "js/jquery-2.1.4.js" %}"></script>
		<script src="{% static "js/scripts.js" %}"></script>
		<table>
			<tr>
				<th>RUC:</th>
				<td><input type="number" id="id_ci" onkeyup="if (event.keyCode == 13) dofind()"></td>
				<td><button onclick="dofind()" type="button">Consultar</button></td>
			</tr>
		</table>
		<br></br>
		<table>
			<tr>
				<th>Nombre/Razón Social:</th>
				<td><label id="id_name"></label></td>
			</tr>
			<tr>
				<th>RUC:</th>
				<td><label id="id_ruc"></label></td>
			</tr>
		</table>
	</body>

</html>